# Generated by Django 4.0.3 on 2022-03-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
                ('broadcast_name', models.CharField(max_length=150, verbose_name='Прередача')),
            ],
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=150, verbose_name='Краткое описание')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
                ('cost_program', models.FloatField(blank=True, verbose_name='Стоимость')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tvad.advertisement', verbose_name='Реклама')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Номер договора')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('telephone', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('money', models.IntegerField(verbose_name='Кошелек')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raring', models.FloatField(blank=True, verbose_name='Стоимость')),
                ('data', models.DateTimeField(blank=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tvad.broadcast', verbose_name='Передача')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tvad.customer', verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tvad.status', verbose_name='Статус рекламы'),
        ),
    ]
