# Generated by Django 4.0.3 on 2022-03-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='broadcast_name',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='raring',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='day_week',
            field=models.IntegerField(default=1, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.FloatField(blank=True, default=1, verbose_name='Рейтинг'),
            preserve_default=False,
        ),
    ]
