# Generated by Django 4.0.3 on 2022-03-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tvad', '0003_remove_broadcast_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='advertisement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tvad.advertisement', verbose_name='Реклама'),
            preserve_default=False,
        ),
    ]
