# Generated by Django 4.0.3 on 2022-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvad', '0004_broadcast_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='duration',
            field=models.FloatField(verbose_name='Продолжительность'),
        ),
    ]
