# Generated by Django 4.0.3 on 2022-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvad', '0005_alter_advertisement_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_details',
            field=models.CharField(default=0, max_length=200, verbose_name='Банковские реквизиты'),
            preserve_default=False,
        ),
    ]
