# Generated by Django 4.0.3 on 2022-04-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvad', '0006_customer_bank_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='number_repetitions',
            field=models.IntegerField(default=1, verbose_name='Количество повторов'),
            preserve_default=False,
        ),
    ]
